name: gorgon
version: 0.8.0
author: Cantidio Oliveira Fontes
description: A game development lib.
homepage: https://github.com/cantidio/gorgonDart
dependencies:
  js: any
  browser: any
  web_ui: any
  async: any
dev_dependencies:
  unittest: any
